[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "WeatherTweaks"
description = "Difficulty tweaks to the weather system in Lethal Company."
websiteUrl = "https://github.com/AndreyMrovol/LethalWeatherTweaks"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
mrov-WeatherRegistry = "0.5.1"
xilophor-LethalNetworkAPI = "3.3.1"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../WeatherTweaks/dist"

[[build.copy]]
source = "../WeatherTweaks/bin/Release/netstandard2.1/WeatherTweaks.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[[build.copy]]
source = "../Opensource.md"
target = "/"

[publish]
communities = [ "lethal-company", ]